organizer/urls.py
from django.urls import path
from . import views

app_name = 'organizer'

urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('<int:pk>/', views.DetailView.as_view(), name='detail'),
    path('new/', views.CreateView.as_view(), name='create'),
    path('<int:pk>/edit/', views.UpdateView.as_view(), name='update'),
    path('<int:pk>/delete/', views.DeleteView.as_view(), name='delete'),
]

project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('organizer/', include('organizer.urls'))
]

organizer/models.py
from django.core.exceptions import ValidationError
from django.core.validators import MinValueValidator
from django.db import models
from django.urls import reverse
from django.utils import timezone

def no_past(value):
    today = timezone.now()
    if value < today:
        raise ValidationError('Date & time cannot be in the past.')


class Task(models.Model):
    complete = models.BooleanField(default=False)
    description = models.CharField(max_length=256)
    time_estimate = models.IntegerField(validators=[MinValueValidator(0)])
    due_date = models.DateTimeField(validators=[no_past])

    def __str__(self):
        return self.description

    def get_absolute_url(self):
        return reverse('organizer:detail', kwargs={'pk': self.pk})

organizer/forms.py
from django import forms
from . import models

class TaskForm(forms.ModelForm):
    class Meta:
        model = models.Task

organizer/views.py
from django.http import HttpResponse, Http404
from django.shortcuts import render, get_object_or_404
from django.urls import reverse_lazy
from django.views import generic
# from django.template import loader
from .models import Task

class IndexView(generic.ListView):
    def get_queryset(self):
        return Task.objects.filter(complete=False)[:15]

class DetailView(generic.DetailView):
    model = Task

class CreateView(generic.CreateView):
    model = Task
    fields = ['description', 'time_estimate', 'due_date']

class UpdateView(generic.UpdateView):
    model = Task
    fields = ['description', 'time_estimate', 'due_date', 'complete']

class DeleteView(generic.DeleteView):
    model = Task
    success_url = reverse_lazy('organizer:index')

organizer/templates/organizer/detail.html
{{ task }}

organizer/templates/organizer/index.html
{% if task_list %}
  <ul>
    {% for task in task_list %}
      <li><a href="{% url 'organizer:detail' task.id %}">{{ task.description }}</a></li>
    {% endfor %}
  </ul>
{% else %}
  <p> No tasks are available </p>
{% endif %}

organizer/templates/organizer/task_confirm_delete.html
<form method="post">{% csrf_token %}
  <p>Are you sure you want to delete "{{ task }}"?</p>
  <input type="submit" value="Confirm" />
</form>

organizer/templates/organizer/task_detail.html
{{ task }}

<p><a href="{% url 'organizer:delete' task.id %}">delete the task</a></p>

organizer/templates/organizer/task_form.html
<form method="post">{% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Save" />
</form>

organizer/templates/organizer/task_list.html
{% if task_list %}
  <ul>
    {% for task in task_list %}
      <li><a href="{% url 'organizer:detail' task.id %}">{{ task.description }}</a></li>
    {% endfor %}
  </ul>
{% else %}
  <p> No tasks are available </p>
{% endif %}
<a href="{% url 'organizer:create' %}">create a new task</a>